skrat: PdfGraphicsView Class Reference
PdfGraphicsView Class Reference final
#include <PdfGraphicsView.h>
Classes
struct PageItem
Per-page scene bookkeeping: pixmap item, bounds, PDF size, and scale.
Public Types
enum class ZoomMode { Custom , FitToWidth , FitInView }
How page scale is derived from viewport size versus an explicit zoom factor.
enum class PageMode { SinglePage , MultiPage }
Page layout policy (single vs multi); scene currently always stacks pages vertically.
Signals
void currentPageChanged (int page)
Emitted when the page nearest the viewport vertical center changes.
void currentSearchResultIndexChanged (int index)
Emitted when the highlighted search-result index changes.
Public Member Functions
PdfGraphicsView (QWidget *parent=nullptr)
Constructs the PDF graphics view, scene, and scroll-bar current-page wiring.
void setDocument (QPdfDocument *document)
Attaches a PDF document, connects status signals, and rebuilds the scene.
QPdfDocument * document () const
Returns the document currently bound to this view.
void setSearchModel (QPdfSearchModel *searchModel)
Sets the search model whose rows define highlight rectangles on pages.
QPdfSearchModel * searchModel () const
Returns the active search model.
void setPageMode (PageMode mode)
Stores the page layout mode for API compatibility (layout is vertical stack).
PageMode pageMode () const
Returns the stored page layout mode.
void setZoomMode (ZoomMode mode)
Sets zoom mode, scrollbar policy, and rebuilds layout when fit sizing changes.
ZoomMode zoomMode () const
Returns the active zoom mode.
void setZoomFactor (qreal factor)
Sets the custom zoom factor (only affects layout when mode is Custom).
qreal zoomFactor () const
Returns the current custom zoom factor.
int pageSpacing () const
Vertical gap between stacked pages in scene coordinates (pixels).
int currentPage () const
0-based index of the page whose vertical center is nearest the viewport center.
void jumpTo (int page, const QPointF &location=QPointF(0, 0), qreal zoom=0.0)
Scrolls so page and location are visible; optionally applies zoom in Custom mode.
int currentSearchResultIndex () const
Index of the search result drawn with the “current” highlight color.
void setCurrentSearchResultIndex (int index)
Highlights result index and emits currentSearchResultIndexChanged when it changes.
bool copySelectionToClipboard ()
Copies trimmed text from the multi-page drag selection to the system clipboard.
bool hasTextSelection () const
Whether the user has a latched text selection after a completed drag.
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Relayouts rasterized pages when fit modes depend on viewport size.
void scrollContentsBy (int dx, int dy) override
In fit modes, scrolls vertically only and pins horizontal offset; may clear selection.
void wheelEvent (QWheelEvent *event) override
Forwards the wheel event and clears stale selection when not actively dragging.
void mousePressEvent (QMouseEvent *event) override
Starts a left-button text drag at the PDF coordinates under the cursor.
void mouseMoveEvent (QMouseEvent *event) override
Updates the selection end point and auto-scrolls near viewport edges while dragging.
void mouseReleaseEvent (QMouseEvent *event) override
Ends text selection on left-button release and recomputes highlight state.
Private Member Functions
void clearScene ()
Clears the scene and internal page/search/selection item lists.
void rebuildPages ()
Rasterizes every document page into the scene according to zoom mode.
void rebuildSearchHighlights ()
Rebuilds search-match rectangles from m_searchModel and m_currentSearchResultIndex.
void rebuildTextSelectionHighlights ()
Rebuilds blue selection polygons from anchor/caret PDF geometry.
QRectF mapPdfRectToSceneRect (int page, const QRectF &pdfRect) const
Maps a PDF-space rectangle on one page into scene coordinates.
QPointF mapPdfPointToScenePoint (int page, const QPointF &pdfPoint) const
Maps a PDF-space point on one page into scene coordinates.
QPointF mapScenePointToPdfPoint (int page, const QPointF &scenePoint) const
Maps a scene point into PDF-space for a known page.
bool scenePointToPdfPoint (const QPointF &scenePoint, int *page, QPointF *pdfPoint) const
Resolves a scene position to a page index and clamped PDF coordinates.
QPointF clampPdfPointToPage (int page, const QPointF &pdfPoint) const
Clamps a PDF-space point to the page’s width and height in points.
bool selectionAnchorComesBeforeCurrent () const
Returns whether the selection anchor precedes the caret in document order.
void clearTextSelection ()
Clears drag/selection state and removes selection highlight items.
void updateTextSelection (int page, const QPointF &pdfPoint)
Updates the caret endpoint during a drag and refreshes selection highlights.
bool selectionRangeHasText ()
Returns whether any page in the anchor–caret span has non-empty trimmed selection text.
void updateCurrentPageFromViewport ()
Recomputes m_currentPage from viewport geometry and emits currentPageChanged if needed.
QPdfSelection pdfRangeForPageInSelection (int page, bool isStartPage, bool isEndPage, const QPointF &startPoint, const QPointF &endPoint) const
Builds the QPdfSelection slice for one page within a multi-page drag range.
void syncDocSelectionCharRange ()
Fills m_selDoc* from anchor/caret character indices for index-based spans.
int pdfCharStartIndexAtPoint (int page, const QPointF &pdfPt) const
Probes QPdfDocument::getSelection to find a stable start character index near pdfPt.
int pdfCharInclusiveEndIndexAtPoint (int page, const QPointF &pdfPt) const
Probes getSelection to find an inclusive end character index near pdfPt.
bool selectionAnchorComesBeforeCurrentCharOrder () const
Compares anchor and caret using stored character indices on the same or different pages.
Private Attributes
QPdfDocument * m_document = nullptr
QPdfSearchModel * m_searchModel = nullptr
PageMode m_pageMode = PageMode::MultiPage
ZoomMode m_zoomMode = ZoomMode::FitInView
qreal m_zoomFactor = 1.0
int m_pageSpacingPx = 12
int m_currentPage = 0
int m_currentSearchResultIndex = -1
QGraphicsScene * m_scene = nullptr
QVector< PageItem > m_pages
QList< QGraphicsRectItem * > m_searchHighlights
QList< QGraphicsPolygonItem * > m_textSelectionHighlights
int m_selectionAnchorPage = -1
int m_selectionCurrentPage = -1
QPointF m_selectionAnchorPdf
QPointF m_selectionCurrentPdf
int m_selectionAnchorChar = -1
int m_selectionCurrentChar = -1
int m_selDocFromPage = -1
int m_selDocFromChar = -1
int m_selDocToPage = -1
int m_selDocToChar = -1
bool m_selectingText = false
bool m_hasTextSelection = false
Detailed Description
Definition at line 26 of file PdfGraphicsView.h.
Member Enumeration Documentation
PageMode
enum class PdfGraphicsView::PageMode strong
Enumerator
SinglePage
MultiPage
Definition at line 41 of file PdfGraphicsView.h.
ZoomMode
enum class PdfGraphicsView::ZoomMode strong
Enumerator
Custom
FitToWidth
FitInView
Definition at line 32 of file PdfGraphicsView.h.
Constructor & Destructor Documentation
PdfGraphicsView()
PdfGraphicsView::PdfGraphicsView (QWidget * parent = nullptr) explicit
Parameters
[in] parent Optional parent QWidget.
Member Function Documentation
clampPdfPointToPage()
QPointF PdfGraphicsView::clampPdfPointToPage (int page, const QPointF & pdfPoint) const private
Parameters
[in] page 0-based page index.
[in] pdfPoint Candidate PDF coordinates.
Returns
Clamped point, or (0,0) if page is out of range.
clearScene()
void PdfGraphicsView::clearScene () private
clearTextSelection()
void PdfGraphicsView::clearTextSelection () private
copySelectionToClipboard()
bool PdfGraphicsView::copySelectionToClipboard ()
Returns
true if non-empty text was placed on the clipboard; otherwise false.
currentPage()
int PdfGraphicsView::currentPage () const inline
Returns
Current page index.
Definition at line 122 of file PdfGraphicsView.h.
References m_currentPage.
currentPageChanged
void PdfGraphicsView::currentPageChanged (int page) signal
Parameters
[in] page New 0-based current page index.
currentSearchResultIndex()
int PdfGraphicsView::currentSearchResultIndex () const inline
Returns
0-based model row, or -1 if none / invalid model.
Definition at line 136 of file PdfGraphicsView.h.
References m_currentSearchResultIndex.
currentSearchResultIndexChanged
void PdfGraphicsView::currentSearchResultIndexChanged (int index) signal
Parameters
[in] index New 0-based search model row, or -1 when cleared.
document()
QPdfDocument * PdfGraphicsView::document () const inline
Returns
Pointer to QPdfDocument, or nullptr if none.
Definition at line 62 of file PdfGraphicsView.h.
References m_document.
Referenced by setDocument().
hasTextSelection()
bool PdfGraphicsView::hasTextSelection () const
Returns
true if copySelectionToClipboard() would return text.
jumpTo()
void PdfGraphicsView::jumpTo (int page, const QPointF & location = QPointF(0, 0), qreal zoom = 0.0)
Parameters
[in] page 0-based page index.
[in] location PDF-space point on that page (top-left if default).
[in] zoom If greater than 0 and zoom mode is Custom, passed to setZoomFactor(); otherwise ignored.
mapPdfPointToScenePoint()
QPointF PdfGraphicsView::mapPdfPointToScenePoint (int page, const QPointF & pdfPoint) const private
Parameters
[in] page 0-based page index.
[in] pdfPoint Point in PDF point space.
Returns
Scene coordinates, or (0,0) if page is out of range.
mapPdfRectToSceneRect()
QRectF PdfGraphicsView::mapPdfRectToSceneRect (int page, const QRectF & pdfRect) const private
Parameters
[in] page 0-based page index.
[in] pdfRect Rectangle in PDF point space for that page.
Returns
Corresponding scene rectangle, or null if page is out of range.
mapScenePointToPdfPoint()
QPointF PdfGraphicsView::mapScenePointToPdfPoint (int page, const QPointF & scenePoint) const private
Parameters
[in] page 0-based page index.
[in] scenePoint Point in scene coordinates.
Returns
PDF-space point before clamping to the page box.
mouseMoveEvent()
void PdfGraphicsView::mouseMoveEvent (QMouseEvent * event) override protected
Parameters
[in] event Mouse move event.
mousePressEvent()
void PdfGraphicsView::mousePressEvent (QMouseEvent * event) override protected
Parameters
[in] event Mouse press event.
mouseReleaseEvent()
void PdfGraphicsView::mouseReleaseEvent (QMouseEvent * event) override protected
Parameters
[in] event Mouse release event.
pageMode()
PageMode PdfGraphicsView::pageMode () const inline
Returns
Current PageMode value.
Definition at line 86 of file PdfGraphicsView.h.
References m_pageMode.
pageSpacing()
int PdfGraphicsView::pageSpacing () const inline
Returns
Page spacing in pixels.
Definition at line 116 of file PdfGraphicsView.h.
References m_pageSpacingPx.
pdfCharInclusiveEndIndexAtPoint()
int PdfGraphicsView::pdfCharInclusiveEndIndexAtPoint (int page, const QPointF & pdfPt) const private
Parameters
[in] page 0-based page index.
[in] pdfPt PDF-space reference point.
Returns
Inclusive end character index, or -1 if none found.
pdfCharStartIndexAtPoint()
int PdfGraphicsView::pdfCharStartIndexAtPoint (int page, const QPointF & pdfPt) const private
Parameters
[in] page 0-based page index.
[in] pdfPt PDF-space reference point.
Returns
Start character index, or -1 if none found.
pdfRangeForPageInSelection()
QPdfSelection PdfGraphicsView::pdfRangeForPageInSelection (int page, bool isStartPage, bool isEndPage, const QPointF & startPoint, const QPointF & endPoint) const private
QPdfSelection is per-page; this maps logical anchor/caret across pages to per-page ranges.
Parameters
[in] page 0-based page index to query.
[in] isStartPage true if this page contains the range start point.
[in] isEndPage true if this page contains the range end point.
[in] startPoint PDF-space start of the overall drag (on the start page).
[in] endPoint PDF-space end of the overall drag (on the end page).
Returns
QPdfSelection for page; may be empty if geometry does not intersect text.
rebuildPages()
void PdfGraphicsView::rebuildPages () private
rebuildSearchHighlights()
void PdfGraphicsView::rebuildSearchHighlights () private
rebuildTextSelectionHighlights()
void PdfGraphicsView::rebuildTextSelectionHighlights () private
resizeEvent()
void PdfGraphicsView::resizeEvent (QResizeEvent * event) override protected
Parameters
[in] event Resize event forwarded from Qt.
scenePointToPdfPoint()
bool PdfGraphicsView::scenePointToPdfPoint (const QPointF & scenePoint, int * page, QPointF * pdfPoint) const private
Parameters
[in] scenePoint Point in scene coordinates (e.g. from mapToScene).
[out] page Receives 0-based page index on success.
[out] pdfPoint Receives PDF coordinates clamped to the page media box.
Returns
true if a page could be resolved; false if arguments are null or no pages exist.
scrollContentsBy()
void PdfGraphicsView::scrollContentsBy (int dx, int dy) override protected
Parameters
[in] dx Requested horizontal scroll delta (often suppressed in fit modes).
[in] dy Requested vertical scroll delta.
searchModel()
QPdfSearchModel * PdfGraphicsView::searchModel () const inline
Returns
Pointer to QPdfSearchModel, or nullptr if none.
Definition at line 74 of file PdfGraphicsView.h.
References m_searchModel.
Referenced by setSearchModel().
selectionAnchorComesBeforeCurrent()
bool PdfGraphicsView::selectionAnchorComesBeforeCurrent () const private
Returns
true if anchor is before caret using character indices or geometric fallback.
selectionAnchorComesBeforeCurrentCharOrder()
bool PdfGraphicsView::selectionAnchorComesBeforeCurrentCharOrder () const private
Returns
true if anchor precedes caret in (page, character) order.
selectionRangeHasText()
bool PdfGraphicsView::selectionRangeHasText () private
Returns
true if at least one QPdfSelection in the span has visible text.
setCurrentSearchResultIndex()
void PdfGraphicsView::setCurrentSearchResultIndex (int index)
Parameters
[in] index 0-based QPdfSearchModel row, or -1 to clear the active highlight.
setDocument()
void PdfGraphicsView::setDocument (QPdfDocument * document)
Parameters
[in] document Document to render, or nullptr to clear the view.
References document().
setPageMode()
void PdfGraphicsView::setPageMode (PageMode mode)
Parameters
[in] mode Desired PageMode enum value.
setSearchModel()
void PdfGraphicsView::setSearchModel (QPdfSearchModel * searchModel)
Parameters
[in] searchModel Model from QPdfSearchModel, or nullptr to clear highlights.
References searchModel().
setZoomFactor()
void PdfGraphicsView::setZoomFactor (qreal factor)
Parameters
[in] factor Scale factor; values below an internal minimum are clamped.
setZoomMode()
void PdfGraphicsView::setZoomMode (ZoomMode mode)
Parameters
[in] mode Custom, fit-to-width, or fit-in-view zoom behavior.
syncDocSelectionCharRange()
void PdfGraphicsView::syncDocSelectionCharRange () private
updateCurrentPageFromViewport()
void PdfGraphicsView::updateCurrentPageFromViewport () private
updateTextSelection()
void PdfGraphicsView::updateTextSelection (int page, const QPointF & pdfPoint) private
Parameters
[in] page 0-based page index under the pointer.
[in] pdfPoint PDF-space point on that page (clamped internally).
wheelEvent()
void PdfGraphicsView::wheelEvent (QWheelEvent * event) override protected
Parameters
[in] event Wheel event from Qt.
zoomFactor()
qreal PdfGraphicsView::zoomFactor () const inline
Returns
Stored zoom factor used when mode is Custom.
Definition at line 110 of file PdfGraphicsView.h.
References m_zoomFactor.
zoomMode()
ZoomMode PdfGraphicsView::zoomMode () const inline
Returns
Current ZoomMode value.
Definition at line 98 of file PdfGraphicsView.h.
References m_zoomMode.
Member Data Documentation
m_currentPage
int PdfGraphicsView::m_currentPage = 0 private
Definition at line 345 of file PdfGraphicsView.h.
Referenced by currentPage().
m_currentSearchResultIndex
int PdfGraphicsView::m_currentSearchResultIndex = -1 private
Definition at line 346 of file PdfGraphicsView.h.
Referenced by currentSearchResultIndex().
m_document
QPdfDocument* PdfGraphicsView::m_document = nullptr private
Definition at line 339 of file PdfGraphicsView.h.
Referenced by document().
m_hasTextSelection
bool PdfGraphicsView::m_hasTextSelection = false private
Definition at line 363 of file PdfGraphicsView.h.
m_pageMode
PageMode PdfGraphicsView::m_pageMode = PageMode::MultiPage private
Definition at line 341 of file PdfGraphicsView.h.
Referenced by pageMode().
m_pages
QVector<PageItem> PdfGraphicsView::m_pages private
Definition at line 349 of file PdfGraphicsView.h.
m_pageSpacingPx
int PdfGraphicsView::m_pageSpacingPx = 12 private
Definition at line 344 of file PdfGraphicsView.h.
Referenced by pageSpacing().
m_scene
QGraphicsScene* PdfGraphicsView::m_scene = nullptr private
Definition at line 348 of file PdfGraphicsView.h.
m_searchHighlights
QList<QGraphicsRectItem *> PdfGraphicsView::m_searchHighlights private
Definition at line 350 of file PdfGraphicsView.h.
m_searchModel
QPdfSearchModel* PdfGraphicsView::m_searchModel = nullptr private
Definition at line 340 of file PdfGraphicsView.h.
Referenced by searchModel().
m_selDocFromChar
int PdfGraphicsView::m_selDocFromChar = -1 private
Definition at line 359 of file PdfGraphicsView.h.
m_selDocFromPage
int PdfGraphicsView::m_selDocFromPage = -1 private
Definition at line 358 of file PdfGraphicsView.h.
m_selDocToChar
int PdfGraphicsView::m_selDocToChar = -1 private
Definition at line 361 of file PdfGraphicsView.h.
m_selDocToPage
int PdfGraphicsView::m_selDocToPage = -1 private
Definition at line 360 of file PdfGraphicsView.h.
m_selectingText
bool PdfGraphicsView::m_selectingText = false private
Definition at line 362 of file PdfGraphicsView.h.
m_selectionAnchorChar
int PdfGraphicsView::m_selectionAnchorChar = -1 private
Definition at line 356 of file PdfGraphicsView.h.
m_selectionAnchorPage
int PdfGraphicsView::m_selectionAnchorPage = -1 private
Definition at line 352 of file PdfGraphicsView.h.
m_selectionAnchorPdf
QPointF PdfGraphicsView::m_selectionAnchorPdf private
Definition at line 354 of file PdfGraphicsView.h.
m_selectionCurrentChar
int PdfGraphicsView::m_selectionCurrentChar = -1 private
Definition at line 357 of file PdfGraphicsView.h.
m_selectionCurrentPage
int PdfGraphicsView::m_selectionCurrentPage = -1 private
Definition at line 353 of file PdfGraphicsView.h.
m_selectionCurrentPdf
QPointF PdfGraphicsView::m_selectionCurrentPdf private
Definition at line 355 of file PdfGraphicsView.h.
m_textSelectionHighlights
QList<QGraphicsPolygonItem *> PdfGraphicsView::m_textSelectionHighlights private
Definition at line 351 of file PdfGraphicsView.h.
m_zoomFactor
qreal PdfGraphicsView::m_zoomFactor = 1.0 private
Definition at line 343 of file PdfGraphicsView.h.
Referenced by zoomFactor().
m_zoomMode
ZoomMode PdfGraphicsView::m_zoomMode = ZoomMode::FitInView private
Definition at line 342 of file PdfGraphicsView.h.
Referenced by zoomMode().
The documentation for this class was generated from the following file:
PdfGraphicsView.h