skrat: skrat::PdfDocumentRibbon Class Reference
skrat::PdfDocumentRibbon Class Reference final
Hosts the PDF tool bar with a horizontally centered page label in one row.
Public Member Functions
PdfDocumentRibbon (QToolBar *toolBar, QLabel *pageLabel, QWidget *parent=nullptr)
Constructs the ribbon, reparenting the tool bar and label into this widget.
void recenter ()
Re-runs internal layout after label text or toolbar content changes size.
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Repositions children when the ribbon’s width or height changes.
QSize sizeHint () const override
Returns a preferred height based on toolbar and label size hints.
Private Member Functions
void doLayout ()
Places the tool bar flush left (vertically centered) and centers the page label.
Private Attributes
QToolBar * m_toolBar = nullptr
QLabel * m_pageLabel = nullptr
Detailed Description
Definition at line 370 of file MainWindow.cpp.
Constructor & Destructor Documentation
PdfDocumentRibbon()
skrat::PdfDocumentRibbon::PdfDocumentRibbon (QToolBar * toolBar, QLabel * pageLabel, QWidget * parent = nullptr) inline explicit
Parameters
[in] toolBar PDF navigation tool bar (may be nullptr; layout skips nulls).
[in] pageLabel Label showing “Page X of Y”; receives transparent-for-mouse-events.
[in] parent Optional parent for lifetime; usually the preview pane widget.
Definition at line 379 of file MainWindow.cpp.
References m_pageLabel, and m_toolBar.
Member Function Documentation
doLayout()
void skrat::PdfDocumentRibbon::doLayout () inline private
Definition at line 431 of file MainWindow.cpp.
References m_pageLabel, and m_toolBar.
Referenced by recenter(), and resizeEvent().
recenter()
void skrat::PdfDocumentRibbon::recenter () inline
Definition at line 398 of file MainWindow.cpp.
References doLayout().
resizeEvent()
void skrat::PdfDocumentRibbon::resizeEvent (QResizeEvent * event) inline override protected
Parameters
[in] event Qt resize event forwarded to QFrame.
Definition at line 405 of file MainWindow.cpp.
References doLayout().
sizeHint()
QSize skrat::PdfDocumentRibbon::sizeHint () const inline override protected
Returns
Size hint with unconstrained width and at least 34px height.
Definition at line 415 of file MainWindow.cpp.
References m_pageLabel, and m_toolBar.
Member Data Documentation
m_pageLabel
QLabel* skrat::PdfDocumentRibbon::m_pageLabel = nullptr private
Definition at line 453 of file MainWindow.cpp.
Referenced by doLayout(), PdfDocumentRibbon(), and sizeHint().
m_toolBar
QToolBar* skrat::PdfDocumentRibbon::m_toolBar = nullptr private
Definition at line 452 of file MainWindow.cpp.
Referenced by doLayout(), PdfDocumentRibbon(), and sizeHint().
The documentation for this class was generated from the following file:
MainWindow.cpp